spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.36.32:3306/springboot
    username: root
    password: saopigying2018
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

